version: "0.1"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - apache
    networks:
      - docker.network
    volumes:
      - ${PATH_ROOT}:/var/www

  apache:
    build: ./docker/apache
    restart: unless-stopped
    container_name: docker.apache
    tty: true
    ports:
      - 80:80
      - 443:443
    networks:
      - docker.network
    volumes:
      - ${PATH_ROOT}:/var/www

  mariadb:
    image: mariadb
    restart: unless-stopped
    container_name: docker.mariadb
    tty: true
    ports:
      - '3306:3306'
    networks:
      - docker.network
    volumes:
      - ./docker/mysql/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ${PATH_DBROOT}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}

  #mysql:
  #  image: mysql
  #  restart: unless-stopped
  #  container_name: docker.mysql
  #  tty: true
  #  ports:
  #    - '3306:3306'
  #  networks:
  #    - docker.network
  #  volumes:
  #    - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro
  #    - ${PATH_DBROOT}:/var/lib/mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
  #    MYSQL_USER: ${MYSQL_USER:-mysql}
  #    MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}

  phpmyadmin:
    image: phpmyadmin
    container_name: docker.phpmyadmin
    tty: true
    depends_on:
      - php
      - mariadb
    ports:
      - "8080:80"
    networks:
      - docker.network
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
