version: "1.1.0"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - apache
      - mailpit
    networks:
      - docker.network
    volumes:
      - ${PATH_ROOT}:/var/www

  apache:
    build: ./docker/apache
    restart: unless-stopped
    container_name: docker.apache
    tty: true
    ports:
      - 80:80
      - 443:443
    networks:
      - docker.network
    volumes:
      - ${PATH_ROOT}:/var/www

  mariadb:
    build: ./docker/mariadb
    restart: unless-stopped
    container_name: docker.mariadb
    tty: true
    depends_on:
      - apache
    ports:
      - 3306:3306
    networks:
      - docker.network
    volumes:
      - ${PATH_DBROOT}:/var/lib/mysql

  #mysql:
  #  build: ./docker/mysql
  #  restart: unless-stopped
  #  container_name: docker.mysql
  #  tty: true
  #  depends_on:
  #    - apache
  #  ports:
  #    - 3306:3306
  #  networks:
  #    - docker.network
  #  volumes:
  #    - ${PATH_DBROOT}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: docker.phpmyadmin
    tty: true
    depends_on:
      - php
      - mariadb
    ports:
      - 8080:80
    networks:
      - docker.network
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
      PMA_PORT: 3306

  mailpit:
    image: axllent/mailpit
    # container_name = SMTP host!
    container_name: docker.mailpit
    tty: true
    depends_on:
      - apache
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - docker.network
    environment:
      MP_QUIET: 1
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
