version: "1.2.0"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - apache
      - mailpit
    networks:
      - docker.network
    volumes:
      - ${PATH_SITE}:/var/www/public_html
      - ${PATH_LOGS_PHP}:/var/log/php
    environment:
      HOST: ${HOST}
    extra_hosts:
      - host.docker.internal:host-gateway

  apache:
    build: ./docker/apache
    restart: unless-stopped
    container_name: docker.apache
    tty: true
    ports:
      - 80:80
      - 443:443
    networks:
      - docker.network
    volumes:
      - ${PATH_SITE}:/var/www/public_html
      - ${PATH_LOGS_APACHE}:/var/log/apache
    environment:
      SERVER_NAME: ${HOST}

  mariadb:
    build: ./docker/mariadb
    restart: unless-stopped
    container_name: docker.mariadb
    tty: true
    depends_on:
      - apache
    ports:
      - 3306:3306
    networks:
      - docker.network
    volumes:
      - ${PATH_DBROOT}:/var/lib/mysql
      - ${PATH_LOGS_MARIADB}:/var/log/mariadb
    environment:
      HOST: ${HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}

  #mysql:
  #  build: ./docker/mysql
  #  restart: unless-stopped
  #  container_name: docker.mysql
  #  tty: true
  #  depends_on:
  #    - apache
  #  ports:
  #    - 3306:3306
  #  networks:
  #    - docker.network
  #  volumes:
  #    - ${PATH_DBROOT}:/var/lib/mysql
  #    - ${PATH_LOGS_MYSQL}:/var/log/mysql
  #  environment:
  #    HOST: ${HOST}
  #    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
  #    MYSQL_USER: ${MYSQL_USER:-mysql}
  #    MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}

  phpmyadmin:
    image: phpmyadmin
    container_name: docker.phpmyadmin
    tty: true
    depends_on:
      - php
      - mariadb
    ports:
      - 8080:80
    networks:
      - docker.network
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
      PMA_PORT: 3306

  mailpit:
    image: axllent/mailpit
    # container_name = SMTP host!
    container_name: docker.mailpit
    tty: true
    depends_on:
      - apache
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - docker.network
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
